fix: Ensure install the target in configure (especially for windows gnu)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -70,13 +70,8 @@ So using the rust-toolchain.toml file to set the toolchain.
 --------------------------------------------------------------------
 EOF
     export TARGET="wasm32-unknown-emscripten"
-    export FEATURES="${FEATURES:-"nightly"}"
+    FEATURES="${FEATURES:-"nightly"}"
     copy_rust_toolchain_toml
-    # rust-src is needed for Emscripten builds
-    root_dir="$(pwd)"
-    cd "${root_dir}/src" || true
-    rustup component add rust-src
-    cd "${root_dir}" || true
   fi
 }
 
@@ -181,6 +176,13 @@ So using the rust-toolchain.toml file to set the toolchain.
 --------------------------------------------------------------------
 EOF
     copy_rust_toolchain_toml
+
+    # Try to add the target
+    # TODO: Tier 2 without Host Tools support
+    root_dir="$(pwd)"
+    cd "${root_dir}/src" || true
+    rustup target add "${TARGET}" || echo "Failed to add target ${TARGET}."
+    cd "${root_dir}" || true
   fi
 }
 
@@ -194,12 +196,15 @@ fi
 # Ensure run bootstrap.R
 "${R_HOME}/bin${R_ARCH_BIN}/Rscript" "bootstrap.R"
 
+check_emscripten
 check_bin_lib
 check_cargo
-check_emscripten
+
+# This needs rustc to be installed
+TARGET="${TARGET:-$(rustc -vV | grep host | cut -d' ' -f2)}"
+
+# They need the TARGET to be set
 check_feature
 check_rustup
-
-TARGET="${TARGET:-$(rustc -vV | grep host | cut -d' ' -f2)}"
 
 generate_makevars
