fix: add rust-src only for emscripten

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -183,6 +183,11 @@ EOF
     root_dir="$(pwd)"
     cd "${root_dir}/src" || true
     rustup target add "${TARGET}" || echo "Failed to add target ${TARGET}."
+
+    # For Emscripten build, the rust-src is needed for to include the stdlib to reduce the size of the binary.
+    if [ "${TARGET}" = "wasm32-unknown-emscripten" ]; then
+      rustup component add rust-src || echo "Failed to add rust-src."
+    fi
     cd "${root_dir}" || true
   fi
 }
